import { setHours } from 'date-fns';

import { TaskData } from './Calendar.types';

export const dummySchedules: TaskData[] = [
  {
    id: 1,
    title: 'title',
    description: 'description',
    startDate: setHours(new Date(), 9),
    endDate: setHours(new Date(), 10),
    status: 0,
  },
  {
    id: 2,
    title: 'title',
    description: 'description',
    startDate: setHours(new Date(), 10),
    endDate: setHours(new Date(), 11),
    status: 0,
  },
  {
    id: 3,
    title: 'title',
    description: 'description',
    startDate: setHours(new Date(), 11),
    endDate: setHours(new Date(), 12),
    status: 0,
  },
  {
    id: 4,
    title: 'title',
    description: 'description',
    startDate: setHours(new Date(), 12),
    endDate: setHours(new Date(), 13),
    status: 0,
  },
  {
    id: 5,
    title: 'title',
    description: 'description',
    startDate: setHours(new Date(), 13),
    endDate: setHours(new Date(), 14),
    status: 0,
  },
  {
    id: 6,
    title: 'title',
    description: 'description',
    startDate: setHours(new Date(), 14),
    endDate: setHours(new Date(), 15),
    status: 2,
  },
  {
    id: 7,
    title: 'title',
    description: 'description',
    startDate: setHours(new Date(), 15),
    endDate: setHours(new Date(), 16),
    status: 1,
  },
  {
    id: 8,
    title: 'title',
    description: 'description',
    startDate: setHours(new Date(), 16),
    endDate: setHours(new Date(), 17),
    status: 0,
  },
  {
    id: 9,
    title: 'title',
    description: 'description',
    startDate: setHours(new Date(), 17),
    endDate: setHours(new Date(), 18),
    status: 0,
  },
  {
    id: 10,
    title: 'title',
    description: 'description',
    startDate: setHours(new Date(), 18),
    endDate: setHours(new Date(), 19),
    status: 0,
  },
];
